# Site
title:              Inova Joinville
bio:                'Grupo de quem faz acontecer \o/'
description:        "O Inova é um movimento independente que promove ações para o bem-estar social, ambiental e econômico das pessoas e de joinville"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo_colorida.png'
background:         'assets/img/placeholder-big.jpg'
locale:             pt_BR
url:                http://inovajoinville.github.io/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   inovajoinville

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
twitter:            inovajoinville
facebook:           inovajoinville
github:             inovajoinville
#stackoverflow:      123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:           username
#xing:              username
instagram:          inovajoinville
#lastfm:             username
#tumblr:             username
#pinterest:         username
#foursquare:        username
#dribbble:          username
#youtube:            username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
