# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Inova Joinville
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  O inova é um movimento independente que promove ações para o bem-estar social, ambiental e econômico das pessoas e de joinville
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://inovajoiville.github.io" # the base hostname & protocol for your site
facebook_username: inovajoiville
twitter_username: inovajoiville
github_username:  inovajoiville
paginate: 3
paginate_path: "/posts/page:num/"

# Build settings
markdown: kramdown
# exclude: [node_modules, gulpfile.js]
gems: [jekyll-paginate]